package net.luderspieler.dnd.character.AbilitysAndFeats.management;

public enum Ability {
    // ==========================================
    // SHARED ABILITIES (Used by multiple classes)
    // ==========================================
    EVASION,
    UNARMORED_DEFENSE,
    WEAPON_MASTERY,

    // ==========================================
    // CLASS ABILITIES
    // ==========================================

    // --- BARBARIAN ---
    BRUTAL_STRIKE,
    DANGER_SENSE,
    EXTRA_ATTACK_BARBARIAN,
    FAST_MOVEMENT,
    FERAL_INSTINCT,
    IMPROVED_BRUTAL_STRIKE_ONE,
    IMPROVED_BRUTAL_STRIKE_TWO,
    INDOMITABLE_MIGHT,
    INSTINCTIVE_POUNCE,
    PERSISTENT_RAGE,
    PRIMAL_CHAMPION,
    PRIMAL_KNOWLEDGE,
    RAGE,
    RECKLESS_ATTACK,
    RELENTLESS_RAGE,

    // --- BARD ---
    BARDIC_INSPIRATION,
    EXPERTISE,
    FONT_OF_INSPIRATION,
    IMPROVED_EXPERTISE_ONE,
    JACK_OF_ALL_TRADES,
    MAGICAL_SECRETS,
    PEERLESS_SKILL,
    SPELLCASTING_BARD,
    SUPERIOR_INSPIRATION,
    WORDS_OF_CREATION,

    // --- CLERIC ---
    BLESSED_STRIKES,
    CHANNEL_DIVINITY,
    DIVINE_INTERVENTION,
    DIVINE_ORDER,
    IMPROVED_BLESSED_STRIKES_ONE,
    IMPROVED_DIVINE_INTERVENTION_ONE,
    SMITE_UNDEAD,
    SPELLCASTING_CLERIC,

    // --- DRUID ---
    ARCHDRUID,
    BEAST_SPELLS,
    DRUIDIC,
    ELEMENTAL_FURY,
    IMPROVED_ELEMENTAL_FURY_ONE,
    PRIMAL_ORDER,
    SPELLCASTING_DRUID,
    WILD_COMPANION,
    WILD_RESURGENCE,
    WILD_SHAPE,

    // --- FIGHTER ---
    ACTION_SURGE,
    EXTRA_ATTACK_FIGHTER,
    FIGHTING_STYLE,
    IMPROVED_ACTION_SURGE_ONE,
    IMPROVED_EXTRA_ATTACK_FIGHTER_ONE,
    IMPROVED_EXTRA_ATTACK_FIGHTER_TWO,
    IMPROVED_INDOMITABLE_ONE,
    IMPROVED_INDOMITABLE_TWO,
    INDOMITABLE,
    SECOND_WIND,
    STUDIED_ATTACKS,
    TACTICAL_MASTER,
    TACTICAL_MIND,
    TACTICAL_SHIFT,

    // --- MONK ---
    BODY_AND_MIND,
    DEFLECT_ATTACKS,
    DEFLECT_ENERGY,
    DIAMOND_SOUL,
    EMPOWERED_STRIKES,
    EXTRA_ATTACK_MONK,
    FOCUS_POINTS,
    IMPROVED_UNARMORED_MOVEMENT_ONE,
    MARTIAL_ARTS,
    PERFECT_BODY,
    SELF_RESTORATION,
    SLOW_FALL,
    STUNNING_STRIKE,
    UNARMORED_MOVEMENT,
    UNCANNY_METABOLISM,

    // --- PALADIN ---
    ABJURE_FOES,
    ARCH_PALADIN,
    AURA_OF_COURAGE,
    AURA_OF_PROTECTION,
    CHANNEL_DIVINITY_PALADIN,
    EXTRA_ATTACK_PALADIN,
    FIGHTING_STYLE_PALADIN,
    IMPROVED_AURA_OF_PROTECTION_ONE,
    LAY_ON_HANDS,
    PALADINS_SMITE,
    RADIANT_SMITE,
    RESTORING_TOUCH,
    SPELLCASTING_PALADIN,

    // --- RANGER ---
    DEFT_EXPLORER,
    EXTRA_ATTACK_RANGER,
    FAVORED_ENEMY,
    FERAL_SENSES,
    FIGHTING_STYLE_RANGER,
    FOE_SLAYER,
    IMPROVED_DEFT_EXPLORER_ONE,
    NATURES_VEIL,
    RELENTLESS_HUNTER,
    ROVING,
    SPELLCASTING_RANGER,
    TIRELESS,

    // --- ROGUE ---
    CUNNING_ACTION,
    CUNNING_STRIKE,
    ELUSIVE,
    EXPERTISE_ROGUE,
    IMPROVED_CUNNING_STRIKE_ONE,
    IMPROVED_CUNNING_STRIKE_TWO,
    IMPROVED_EXPERTISE_ROGUE_ONE,
    RELIABLE_TALENT,
    SLIPPERY_MIND,
    SNEAK_ATTACK,
    STEADY_AIM,
    STROKE_OF_LUCK,
    THIEVES_CANT,
    UNCANNY_DODGE,

    // --- SORCERER ---
    FONT_OF_MAGIC,
    INNATE_SORCERY,
    METAMAGIC,
    SORCEROUS_APOTHEOSIS,
    SORCEROUS_BURST,
    SORCEROUS_INCARNATION,
    SORCEROUS_RESTORATION,
    SPELLCASTING_SORCERER,

    // --- WARLOCK ---
    ELDRITCH_INVOCATIONS,
    ELDRITCH_MASTER,
    IMPROVED_MYSTIC_ARCANUM_ONE,
    IMPROVED_MYSTIC_ARCANUM_THREE,
    IMPROVED_MYSTIC_ARCANUM_TWO,
    MAGICAL_CUNNING,
    MYSTIC_ARCANUM,
    PACT_MAGIC,

    // --- WIZARD ---
    ARCANE_RECOVERY,
    MEMORIZE_SPELLS,
    SCHOLAR,
    SIGNATURE_SPELLS,
    SPELL_MASTERY,
    SPELLCASTING_WIZARD,


    // ==========================================
    // SPECIES / RACE & SUBRACE ABILITIES
    // ==========================================

    // --- HUMAN ---
    RESOURCEFUL,
    VERSATILE,

    // --- DWARF ---
    DARKVISION_DWARF,
    DWARVEN_RESILIENCE,
    DWARVEN_TOUGHNESS,
    STONE_CUNNING,

    // --- ELF (Base & Lineages) ---
    DARKVISION_DROW,
    DARKVISION_ELF,
    DROW_LINEAGE,
    ELVEN_LINEAGE,
    FEY_ANCESTRY,
    HIGH_ELF_LINEAGE,
    KEEN_SENSES,
    SPEED_WOOD_ELF,
    TRANCE,
    WOOD_ELF_LINEAGE,

    // --- HALFLING ---
    BRAVE,
    HALFLING_NIMBLENESS,
    LUCKY,
    NATURALLY_STEALTHY,

    // --- DRAGONBORN ---
    BREATH_WEAPON,
    DAMAGE_RESISTANCE_DRAGONBORN,
    DARKVISION_DRAGONBORN,
    DRACONIC_ANCESTRY,
    FLIGHT,

    // --- GNOME (Base & Lineages) ---
    DARKVISION_GNOME,
    FOREST_GNOME_LINEAGE,
    GNOME_CUNNING,
    GNOMISH_LINEAGE,
    ROCK_GNOME_LINEAGE,

    // --- AASIMAR ---
    CELESTIAL_RESISTANCE,
    CELESTIAL_REVELATION,
    DARKVISION_AASIMAR,
    HEALING_HANDS,
    LIGHT_BEARER,

    // --- TIEFLING (Base & Lineages) ---
    ABYSSAL_LINEAGE,
    CHTHONIC_LINEAGE,
    DARKVISION_TIEFLING,
    FIENDISH_RESISTANCE,
    INFERNAL_LINEAGE,
    OTHERWORLDLY_GIFT,

    // --- GOLIATH (Base & Lineages) ---
    CLOUDS_JAUNT,
    FIRES_BURN,
    FROSTS_CHILL,
    GIANT_ANCESTRY,
    HILLS_TUMBLE,
    LARGE_FORM,
    POWERFUL_BUILD,
    SPEED_GOLIATH,
    STONES_ENDURANCE,
    STORMS_THUNDER,

    // --- ORC ---
    ADRENALINE_RUSH,
    DARKVISION_ORC,
    POWERFUL_BUILD_ORC,
    RELENTLESS_ENDURANCE;

    /**
     * Gibt eine lesbare Version des Enum-Namens zurück
     */
    public String getDisplayName() {
        return this.name().replace("_", " ");
    }
}

/*
// ==================== BARBARIAN ====================
    RAGE,
    RECKLESS_ATTACK,
    DANGER_SENSE,
    PRIMAL_KNOWLEDGE,
    EXTRA_ATTACK_BARBARIAN,
    FERAL_INSTINCT,
    BRUTAL_CRITICAL,
    RELENTLESS_RAGE,
    PRIMAL_REFLEXES,
    RELENTLESS,
    PRIMAL_CHAMPION,

    // ==================== BARD ====================
    BARDIC_INSPIRATION,
    SPELLCASTING_BARD,
    JACK_OF_ALL_TRADES,
    EXPERTISE,
    FONT_OF_INSPIRATION,
    COUNTERCHARM,
    MAGICAL_SECRETS_BARD,
    PEERLESS_SKILL,
    LEGENDARY_PERFORMANCE,
    SUPERIOR_INSPIRATION,

    // ==================== CLERIC ====================
    SPELLCASTING_CLERIC,
    CHANNEL_DIVINITY,
    HEALING_WORD_IMPROVEMENT,
    DESTROY_UNDEAD,
    POTENT_SPELLCASTING,
    IMPROVED_CHANNEL_DIVINITY,
    DIVINE_STRIKE,
    SUPREME_HEALING,
    DIVINE_INTERVENTION,

    // ==================== DRUID ====================
    SPELLCASTING_DRUID,
    DRUIDIC,
    WILD_SHAPE,
    WILD_COMPANION,
    WILD_FIRE,
    IMPROVED_WILD_SHAPE,
    BEAST_SPELLS,
    THOUSAND_FORMS,
    UNLIMITED_WILD_SHAPE,

    // ==================== FIGHTER ====================
    FIGHTING_STYLE,
    SECOND_WIND,
    ACTION_SURGE,
    MARTIAL_ARCHETYPE,
    EXTRA_ATTACK_FIGHTER,
    INDOMITABLE,
    EXTRA_ATTACK_FIGHTER_2,
    SUDDEN_STRIKE,
    SUPERIOR_CRITICAL,
    ACTION_SURGE_MASTERY,
    EXTRA_ATTACK_FIGHTER_3,

    // ==================== MONK ====================
    MARTIAL_ARTS,
    UNARMORED_DEFENSE,
    KI,
    UNARMORED_MOVEMENT,
    MONASTIC_TRADITION,
    SLOW_FALL,
    EXTRA_ATTACK_MONK,
    STUNNING_STRIKE,
    KI_FUELED_ATTACK,
    EVASION,
    PURITY_OF_BODY,
    TONGUE_OF_THE_SUN_AND_MOON,
    DIAMOND_SOUL,
    TIMELESS_BODY,
    EMPTY_BODY,
    PERFECT_SELF,

    // ==================== PALADIN ====================
    LAY_ON_HANDS,
    SPELLCASTING_PALADIN,
    FIGHTING_STYLE_PALADIN,
    CHANNEL_DIVINITY_PALADIN,
    DIVINE_SMITE,
    AURA_OF_PROTECTION,
    BLESSED_WARRIOR,
    AURA_OF_COURAGE,
    IMPROVED_SMITE,
    CLEANSING_TOUCH,
    AURA_IMPROVEMENTS,

    // ==================== RANGER ====================
    DRAKEWARDEN,
    SPELLCASTING_RANGER,
    FIGHTING_STYLE_RANGER,
    RANGERS_QUARRY,
    PRIMAL_ORDER,
    EXTRA_ATTACK_RANGER,
    ROVING,
    PRIMAL_AWARENESS,
    RANGERS_INTUITION,
    FLEET_OF_FOOT,
    FERAL_SENSES,
    FOE_SLAYER,

    // ==================== ROGUE ====================
    EXPERTISE_ROGUE,
    SNEAK_ATTACK,
    CUNNING_ACTION,
    ROGUISH_ARCHETYPE,
    UNCANNY_DODGE,
    EXPERTISE_EXPANSION,
    REMARKABLE_DODGE,
    RELIABLE_TALENT,
    BLINDSENSE,
    SLIPPERY_MIND,
    ELUSIVE,
    STROKE_OF_LUCK,

    // ==================== SORCERER ====================
    SPELLCASTING_SORCERER,
    SORCEROUS_RESILIENCE,
    FONT_OF_MAGIC,
    METAMAGIC,
    MAGICAL_GUIDANCE,
    SORCEROUS_VERSATILITY,
    MAGICAL_AMPLIFICATION,
    MAGICAL_EPIPHANY,
    SORCEROUS_RESTORATION,

    // ==================== WARLOCK ====================
    PACT_MAGIC,
    OTHERWORLDLY_PATRON,
    ELDRITCH_INVOCATIONS,
    PACT_BOON,
    CONTACT_OTHER_PLANE,
    ELDRITCH_VERSATILITY,
    MYSTIC_ARCANUM,
    ELDRITCH_MASTER,
    ELDRITCH_MASTER_MASTERY,

    // ==================== WIZARD ====================
    SPELLCASTING_WIZARD,
    ARCANE_RECOVERY,
    ARCANE_TRADITION,
    SPELL_MASTERY,
    SIGNATURE_SPELLS,

    // ==================== RACE: HUMAN ====================
    EXTRA_ABILITY_INCREASE_HUMAN,

    // ==================== RACE: DWARF ====================
    DWARVEN_RESILIENCE,
    DWARVEN_COMBAT_TRAINING,
    TOOL_PROFICIENCY_DWARF,

    // ==================== RACE: ELF ====================
    KEEN_SENSES_ELF,
    FEY_ANCESTRY,
    TRANCE,

    // ==================== RACE: HALFLING ====================
    NATURALLY_STEALTHY,
    FORTUNATE,

    // ==================== RACE: DRAGONBORN ====================
    DRACONIC_RESILIENCE,
    DRACONIC_ANCESTRY,

    // ==================== RACE: GNOME ====================
    GNOME_CUNNING,

    // ==================== RACE: AASIMAR ====================
    CELESTIAL_RESISTANCE,
    HEALING_HANDS,

    // ==================== RACE: TIEFLING ====================
    INFERNAL_RESILIENCE,
    HELLISH_RESISTANCE,

    // ==================== RACE: GOLIATH ====================
    STONE_ENDURANCE,
    POWERFUL_BUILD,

    // ==================== RACE: ORC ====================
    ORC_POWERFUL_BUILD,
    PRIMAL_INTUITION,

    // ==================== SUBRACE: ELF - HIGH ELF ====================
    EXTRA_CANTRIP_HIGH_ELF,

    // ==================== SUBRACE: ELF - WOOD ELF ====================
    MASK_OF_THE_WILD,

    // ==================== SUBRACE: ELF - DROW ====================
    SUNLIGHT_SENSITIVITY,
    DROW_SPELLCASTING,

    // ==================== SUBRACE: DWARF - MOUNTAIN ====================
    ARMOR_TRAINING_MOUNTAIN_DWARF,

    // ==================== SUBRACE: DWARF - HILL ====================
    HILL_DWARF_ABILITY_INCREASE,

    // ==================== SUBRACE: HALFLING - LIGHTFOOT ====================
    // Uses base halfling abilities

    // ==================== SUBRACE: HALFLING - STOUT ====================
    STOUT_RESILIENCE,

    // ==================== SUBRACE: DRAGONBORN - CHROMATIC ====================
    CHROMATIC_BREATH_WEAPON,
    CHROMATIC_DAMAGE_RESISTANCE,

    // ==================== SUBRACE: DRAGONBORN - METALLIC ====================
    METALLIC_BREATH_WEAPON,
    METALLIC_DAMAGE_RESISTANCE,

    // ==================== SUBRACE: DRAGONBORN - GEM ====================
    GEM_BREATH_WEAPON,
    GEM_DAMAGE_RESISTANCE,

    // ==================== SUBRACE: GOLIATH - CLOUD GIANT ====================
    CLOUD_GIANT_ANCESTRY,

    // ==================== SUBRACE: GOLIATH - FIRE GIANT ====================
    FIRE_GIANT_ANCESTRY,

    // ==================== SUBRACE: GOLIATH - FROST GIANT ====================
    FROST_GIANT_ANCESTRY,

    // ==================== SUBRACE: GOLIATH - HILL GIANT ====================
    HILL_GIANT_ANCESTRY,

    // ==================== SUBRACE: GOLIATH - STONE GIANT ====================
    STONE_GIANT_ANCESTRY,

    // ==================== SUBRACE: GOLIATH - STORM GIANT ====================
    STORM_GIANT_ANCESTRY,

    // ==================== SUBRACE: TIEFLING - ABYSSAL ====================
    ABYSSAL_TIEFLING_SPELLS,

    // ==================== SUBRACE: TIEFLING - CHTHONIC ====================
    CHTHONIC_TIEFLING_SPELLS,

    // ==================== SUBRACE: TIEFLING - INFERNAL ====================
    INFERNAL_TIEFLING_SPELLS,

    // ==================== SUBRACE: AASIMAR - CELESTIAL REVELATION ====================
    CELESTIAL_REVELATION_SPELLS,
 */