package net.luderspieler.dnd.character.AbilitysAndFeats.management;

public enum Ability {
    // ==========================================
    // SHARED ABILITIES (Used by multiple classes)
    // ==========================================
    EVASION,
    UNARMORED_DEFENSE,
    WEAPON_MASTERY,
    DARKVISION_120,
    DARKVISION_60,
    SPEED_BONUS_5,

    // ==========================================
    // CLASS ABILITIES
    // ==========================================

    // --- BARBARIAN ---
    BRUTAL_STRIKE,
    DANGER_SENSE,
    EXTRA_ATTACK_BARBARIAN,
    FAST_MOVEMENT,
    FERAL_INSTINCT,
    IMPROVED_BRUTAL_STRIKE_ONE,
    IMPROVED_BRUTAL_STRIKE_TWO,
    INDOMITABLE_MIGHT,
    INSTINCTIVE_POUNCE,
    PERSISTENT_RAGE,
    PRIMAL_CHAMPION,
    PRIMAL_KNOWLEDGE,
    RAGE,
    RECKLESS_ATTACK,
    RELENTLESS_RAGE,

    // --- BARD ---
    BARDIC_INSPIRATION,
    EXPERTISE,
    FONT_OF_INSPIRATION,
    IMPROVED_EXPERTISE_ONE,
    JACK_OF_ALL_TRADES,
    MAGICAL_SECRETS,
    PEERLESS_SKILL,
    SPELLCASTING_BARD,
    SUPERIOR_INSPIRATION,
    WORDS_OF_CREATION,
    COUNTERCHARM,

    // --- CLERIC ---
    BLESSED_STRIKES,
    CHANNEL_DIVINITY,
    DIVINE_INTERVENTION,
    DIVINE_ORDER,
    IMPROVED_BLESSED_STRIKES_ONE,
    IMPROVED_DIVINE_INTERVENTION_ONE,
    SMITE_UNDEAD,
    SPELLCASTING_CLERIC,

    // --- DRUID ---
    ARCHDRUID,
    BEAST_SPELLS,
    DRUIDIC,
    ELEMENTAL_FURY,
    IMPROVED_ELEMENTAL_FURY_ONE,
    PRIMAL_ORDER,
    SPELLCASTING_DRUID,
    WILD_COMPANION,
    WILD_RESURGENCE,
    WILD_SHAPE,

    // --- FIGHTER ---
    ACTION_SURGE,
    EXTRA_ATTACK_FIGHTER,
    FIGHTING_STYLE,
    IMPROVED_ACTION_SURGE_ONE,
    IMPROVED_EXTRA_ATTACK_FIGHTER_ONE,
    IMPROVED_EXTRA_ATTACK_FIGHTER_TWO,
    IMPROVED_INDOMITABLE_ONE,
    IMPROVED_INDOMITABLE_TWO,
    INDOMITABLE,
    SECOND_WIND,
    STUDIED_ATTACKS,
    TACTICAL_MASTER,
    TACTICAL_MIND,
    TACTICAL_SHIFT,

    // --- MONK ---
    BODY_AND_MIND,
    DEFLECT_ATTACKS,
    DEFLECT_ENERGY,
    DIAMOND_SOUL,
    EMPOWERED_STRIKES,
    EXTRA_ATTACK_MONK,
    FOCUS_POINTS,
    IMPROVED_UNARMORED_MOVEMENT_ONE,
    MARTIAL_ARTS,
    PERFECT_BODY,
    ACROBATIC_MOVEMENT,
    HEIGHTENED_FOCUS,
    DISCIPLINED_SURVIVOR,
    PERFECT_FOCUS,
    SUPERIOR_DEFENSE,
    SELF_RESTORATION,
    SLOW_FALL,
    STUNNING_STRIKE,
    UNARMORED_MOVEMENT,
    UNCANNY_METABOLISM,

    // --- PALADIN ---
    ABJURE_FOES,
    ARCH_PALADIN,
    FAITHFUL_STEED,
    RADIANT_STRIKES,
    AURA_EXPANSION,
    AURA_OF_COURAGE,
    AURA_OF_PROTECTION,
    CHANNEL_DIVINITY_PALADIN,
    EXTRA_ATTACK_PALADIN,
    FIGHTING_STYLE_PALADIN,
    IMPROVED_AURA_OF_PROTECTION_ONE,
    LAY_ON_HANDS,
    PALADINS_SMITE,
    RADIANT_SMITE,
    RESTORING_TOUCH,
    SPELLCASTING_PALADIN,

    // --- RANGER ---
    DEFT_EXPLORER,
    EXTRA_ATTACK_RANGER,
    FAVORED_ENEMY,
    FERAL_SENSES,
    FIGHTING_STYLE_RANGER,
    FOE_SLAYER,
    PRECISE_HUNTER,
    IMPROVED_DEFT_EXPLORER_ONE,
    NATURES_VEIL,
    RELENTLESS_HUNTER,
    ROVING,
    SPELLCASTING_RANGER,
    TIRELESS,

    // --- ROGUE ---
    CUNNING_ACTION,
    CUNNING_STRIKE,
    ELUSIVE,
    EXPERTISE_ROGUE,
    IMPROVED_CUNNING_STRIKE_ONE,
    IMPROVED_CUNNING_STRIKE_TWO,
    IMPROVED_EXPERTISE_ROGUE_ONE,
    RELIABLE_TALENT,
    SLIPPERY_MIND,
    SNEAK_ATTACK,
    STEADY_AIM,
    STROKE_OF_LUCK,
    DEVIOUS_STRIKES,
    THIEVES_CANT,
    UNCANNY_DODGE,

    // --- SORCERER ---
    FONT_OF_MAGIC,
    INNATE_SORCERY,
    METAMAGIC,
    SORCEROUS_APOTHEOSIS,
    ARCANE_APOTHEOSIS,
    SORCEROUS_BURST,
    SORCEROUS_INCARNATION,
    SORCEROUS_RESTORATION,
    SPELLCASTING_SORCERER,

    // --- WARLOCK ---
    ELDRITCH_INVOCATIONS,
    ELDRITCH_MASTER,
    CONTACT_PATRON,
    IMPROVED_MYSTIC_ARCANUM_ONE,
    IMPROVED_MYSTIC_ARCANUM_THREE,
    IMPROVED_MYSTIC_ARCANUM_TWO,
    MAGICAL_CUNNING,
    MYSTIC_ARCANUM,
    PACT_MAGIC,

    // --- WIZARD ---
    ARCANE_RECOVERY,
    MEMORIZE_SPELLS,
    SCHOLAR,
    SIGNATURE_SPELLS,
    RITUAL_ADEPT,
    SPELL_MASTERY,
    SPELLCASTING_WIZARD,


    // ==========================================
    // SPECIES / RACE & SUBRACE ABILITIES
    // ==========================================

    // --- HUMAN ---
    RESOURCEFUL,
    VERSATILE,

    // --- DWARF ---
    DWARVEN_RESILIENCE,
    DWARVEN_TOUGHNESS,
    STONE_CUNNING,

    // --- ELF (Base & Lineages) ---
    DROW_LINEAGE,
    ELVEN_LINEAGE,
    FEY_ANCESTRY,
    HIGH_ELF_LINEAGE,
    KEEN_SENSES,
    SPEED_WOOD_ELF,
    TRANCE,
    WOOD_ELF_LINEAGE,

    // --- HALFLING ---
    BRAVE,
    HALFLING_NIMBLENESS,
    LUCKY,
    NATURALLY_STEALTHY,

    // --- DRAGONBORN ---
    BREATH_WEAPON,
    DAMAGE_RESISTANCE_DRAGONBORN,
    DRACONIC_ANCESTRY,
    FLIGHT,

    // --- GNOME (Base & Lineages) ---
    FOREST_GNOME_LINEAGE,
    GNOME_CUNNING,
    GNOMISH_LINEAGE,
    ROCK_GNOME_LINEAGE,

    // --- AASIMAR ---
    CELESTIAL_RESISTANCE,
    CELESTIAL_REVELATION,
    HEALING_HANDS,
    LIGHT_BEARER,

    // --- TIEFLING (Base & Lineages) ---
    ABYSSAL_LINEAGE,
    CHTHONIC_LINEAGE,
    FIENDISH_RESISTANCE,
    INFERNAL_LINEAGE,
    OTHERWORLDLY_GIFT,

    // --- GOLIATH (Base & Lineages) ---
    CLOUDS_JAUNT,
    FIRES_BURN,
    FROSTS_CHILL,
    GIANT_ANCESTRY,
    HILLS_TUMBLE,
    LARGE_FORM,
    POWERFUL_BUILD,
    SPEED_GOLIATH,
    STONES_ENDURANCE,
    STORMS_THUNDER,

    // --- ORC ---
    ADRENALINE_RUSH,
    POWERFUL_BUILD_ORC,
    RELENTLESS_ENDURANCE;

    /**
     * Gibt eine lesbare Version des Enum-Namens zurück
     */
    public String getDisplayName() {
        return this.name().replace("_", " ");
    }
}