package net.luderspieler.dnd.classes;


public enum Ability {
    // --- GEMEINSAME / BASIS ---
    ATTRIBUTE_INCREASE, SUBCLASS_FEATURE, EXTRA_ATTACK, WEAPON_MASTERY,
    FIGHTING_STYLE, EXPERTISE, EVASION, EPIC_BOON, SPELLCASTING,

    // --- BARBARIAN ---
    RAGE, UNARMORED_DEFENSE_BARB, DANGER_SENSE, RECKLESS_ATTACK,
    PRIMAL_KNOWLEDGE, FAST_MOVEMENT, INSTINCTIVE_POUNCE, FERAL_INSTINCT,
    BRUTAL_STRIKE, RELENTLESS_RAGE, PERSISTENT_RAGE, INDOMITABLE_MIGHT, PRIMAL_CHAMPION,

    // --- BARD ---
    BARDIC_INSPIRATION, JACK_OF_ALL_TRADES, FONT_OF_INSPIRATION, COUNTERCHARM,
    MAGICAL_SECRETS, SUPERIOR_INSPIRATION, WORDS_OF_CREATION,

    // --- CLERIC ---
    DIVINE_ORDER, CHANNEL_DIVINITY, SEAR_UNDEAD, BLESSED_STRIKES,
    DIVINE_INTERVENTION, GREATER_DIVINE_INTERVENTION,

    // --- DRUID ---
    PRIMAL_ORDER, WILD_SHAPE, WILD_COMPANION, WILD_RESURGENCE,
    ELEMENTAL_FURY, BEAST_SPELLS, ARCHDRUID,

    // --- FIGHTER ---
    SECOND_WIND, ACTION_SURGE, TACTICAL_MIND, TACTICAL_SHIFT,
    INDOMITABLE, EXTRA_ATTACK_2, EXTRA_ATTACK_3, TACTICAL_MASTER,

    // --- MONK ---
    MARTIAL_ARTS, UNARMORED_DEFENSE_MONK, MONKS_FOCUS, UNCANNY_METABOLISM,
    UNARMORED_MOVEMENT, DEFLECT_ATTACKS, SLOW_FALL, STUNNING_STRIKE,
    EMPOWERED_STRIKES, ACROBATIC_MOVEMENT, HEIGHTENED_FOCUS, SELF_RESTORATION,
    DEFLECT_ENERGY, PERFECT_FOCUS, SUPERIOR_DEFENSE, BODY_AND_MIND,

    // --- PALADIN ---
    LAY_ON_HANDS, PALADINS_SMITE, AURA_OF_PROTECTION, ABJURE_FOES,
    AURA_OF_COURAGE, RADIANT_SMITE, RESTORING_TOUCH, AURA_EXPANSION, OATH_PARAGON, FAITHFUL_STEED,

    // --- RANGER ---
    FAVORED_ENEMY, DEFT_EXPLORER, ROVING, TIRELESS, RELENTLESS_HUNTER,
    NATURE_S_VEIL, PRECISE_HUNTER, FERAL_SENSES, FOE_SLAYER,

    // --- ROGUE ---
    SNEAK_ATTACK, THIEVES_CANT, CUNNING_ACTION, STEADY_AIM,
    CUNNING_STRIKE, UNCANNY_DODGE, RELIABLE_TALENT, DEVIOUS_STRIKES, BLINDSENSE,
    SLIPPERY_MIND, ELUSIVE, STROKE_OF_LUCK,

    // --- SORCERER ---
    INNATE_SORCERY, SORCERY_POINTS, FONT_OF_MAGIC, METAMAGIC,
    SORCEROUS_RESTORATION, SORCERY_INCARNATE, ARCANE_APOTHEOSIS, SORCEROUS_EMINENCE,

    // --- WARLOCK ---
    PACT_MAGIC, PACT_BOON, ELDRITCH_INVOCATIONS, MAGICAL_CUNNING,
    CONTACT_PATRON, MYSTIC_ARCANUM, ELDRITCH_MASTER,

    // --- WIZARD ---
    ARCANE_RECOVERY, SCHOLAR, MEMORIZE_SPELL, SPELL_MASTERY, SIGNATURE_SPELLS, RITUAL_ADEPT,
}